### ISSUE TITLE
Add tests for other cable drivers as well

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/subctl#175]
Currently, subctl tests for default cable driver only. Add tests to run against all PRs for other cable drivers as well.

**Comment by tpantelis** [comment]
We decided to run a minimal set of tests in **subctl**. Also [submariner-operator](https://github.com/submariner-io/submariner-operator/blob/devel/.github/workflows/e2e-full.yml) doesn't even run cable driver tests. The **submariner** repo tests all those.

**Comment by mkolesnik** [comment]
What's the value of having a full e2e matrix?

There's nothing in the e2e tests that actually verifies that any given flag that you set is actually getting deployed (which is a bigger problem but not directly related to this).

You could have simple unit tests to achieve the same goal - see that a flag that you set gets passed down as is to the CR that gets created.
Or if you want you could say that we want to add it to system tests, but since the whole point is to test that a flag gets passed down to a CR I think it's overkill.

**Comment by tpantelis** [comment]
> You could have simple unit tests to achieve the same goal - see that a flag that you set gets passed down as is to the CR that gets created. 

👍

**Comment by dfarrell07** [comment]
Discussing on the PR scrub, it seems to make sense to have system tests in the operator to verify cable drivers we request are deployed and/or to have unit tests in subctl to verify the submariner object's cable driver flag is set properly.

**Comment by dfarrell07** [comment]
Unit test part: https://github.com/submariner-io/subctl/issues/408

**Comment by dfarrell07** [comment]
System tests: https://github.com/submariner-io/submariner-operator/issues/2373
