### ISSUE TITLE
subctl gather doesn’t gather operator logs

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#490]
`subctl gather` should gather the operator’s logs, but it doesn’t.

**Comment by skitt** [comment]
It’s possible this only happens when the operator is deployed using the Submariner addon; it might not have the `name=submariner-operator` label.

**Comment by tpantelis** [comment]
> It’s possible this only happens when the operator is deployed using the Submariner addon; it might not have the `name=submariner-operator` label.

Looking at the [bundle deployment](https://github.com/submariner-io/submariner-operator/blob/4cdbc938a5fd0c7333a85a5a6f00b2f6712bb5f5/bundle/manifests/submariner.clusterserviceversion.yaml#L530), it has a `control-plane` label instead of the `name` label. I suspect the downstream is same/similar. We can make `subctl gather` smarter by obtaining the label to search for from the operator `Deployment`.
