### ISSUE TITLE
subctl verify shouldn’t randomise test order

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#514]
**What happened**:

I ran `subctl verify` several times; each time, the test order varied, which meant the display of skipped tests changed; _e.g._

```
Will run 40 of 44 specs
•••••S•SS••••••••••••SS•••SS•••••SSSSSSSSSSS
```

and

```
Will run 44 of 44 specs
SSSSSSSSSSS•••••S•••••••••••••••••••••S•SS••
```

**What you expected to happen**:

The skipped tests to be consistently displayed.

**How to reproduce it (as minimally and precisely as possible)**:

Run `subctl verify` several times.

**Comment by dfarrell07** [comment]
It might help mitigate this to show the test name, as tracked in https://github.com/submariner-io/subctl/issues/131.

In CI, I think it's a feature to randomize the test order, to make the tests more robust and maybe catch other issues.

But for a user, yes it seems like it's just confusing, makes it harder to compare the output. But we use `subctl verify` in CI, so that complicates things. It seems it would need to be a flag. But as @tpantelis points out, maybe having the random order in places that use `go test` from Shipyard would be enough and the places in CI that use `subctl verify` would not likely be impacted by having deterministic ordering.

**Comment by tpantelis** [comment]
[Ginkgo randomizes](https://onsi.github.io/ginkgo/#spec-randomization) the order of top-level containers and it doesn't look like this is configurable. We can only control randomization of specs in each top-level container which is off by default.

**Comment by skitt** [comment]
Can’t we hard-code the seed, when run from `subctl`?

**Comment by tpantelis** [comment]
> Can’t we hard-code the seed, when run from `subctl`?

yeah we can configure that.
