### ISSUE TITLE
--image-override doesn’t always check the components

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#601]
**What happened**:

On commands such as `subctl diagnose`, specifying an `--image-override` with an invalid component doesn’t produce an error.

**What you expected to happen**:

`subctl join` with an invalid component produces an error; I expected other commands supporting `--image-override` to perform the same check.

**How to reproduce it (as minimally and precisely as possible)**:

`subctl diagnose --image-override=nettest=foo`

(the correct component is `submariner-nettest`).

The check is handled in `MergeImageOverrides`.

**Comment by tpantelis** [comment]
`subctl diagnose --image-override=nettest=foo` actually fails with "_unknown flag: --image-override_" b/c the subcommand is missing. Only certain subcommands support ` --image-override` and they do fail with "_Error determining repository information: invalid override component nettest provided..._" but it's produced during the check, eg:

```
subctl diagnose kube-proxy-mode --image-override=nettest=foo

Cluster "cluster1"
 ✗ Checking Submariner support for the kube-proxy mode
 ✗ Error determining repository information: invalid override component nettest provided. Please choose from ["submariner-operator" "submariner-gateway" "submariner-routeagent" "submariner-globalnet" "submariner-lighthouse-agent" "submariner-lighthouse-coredns" "submariner-nettest" "submariner-metrics-proxy"]
```

Since  ` --image-override` is user input it really should be verified up front so it doesn't appear like a failure with the actual check.
